In [1]:
from keras.models import load_model

Using TensorFlow backend.


In [2]:
model =load_model('task_model.h5')

In [3]:
import cv2

In [4]:
import numpy as np

In [5]:
from PIL import Image

In [6]:
face_model=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [7]:
cap =cv2.VideoCapture(0)

In [8]:
import numpy as np

In [ ]:
while True:
    status ,photo=cap.read()
    face_cor =face_model.detectMultiScale(photo)
    if len(face_cor)==0:
        pass
    else:
        (x,y,w,h)=face_cor[0]
        cv2.rectangle(photo ,(x,y),(x+w ,y+h) ,[0,255,255] ,3)
        crop_img=photo[y:y+h ,x:x+w]
        if type(photo) is np.ndarray:
            crop_img = np.resize(crop_img ,(224,224,3))
            img_array = np.expand_dims(crop_img,axis=0)
            pred = model.predict(img_array)
            print(pred)
            name = 'notmatched'
    
            if pred[0][0]==1. :
                name ='Ravi'
                cv2.putText(photo ,name ,(50,50) ,cv2.FONT_HERSHEY_COMPLEX ,1 ,(0,255,0) ,2)
            else:
                name ='santosh jangid'
                cv2.putText(photo ,name ,(50,50) ,cv2.FONT_HERSHEY_COMPLEX ,1 ,(0,255,0) ,2)
             
    
    cv2.imshow('Video',photo)
    if cv2.waitKey(10)==13:
        break
cv2.destroyAllWindows()
cv2.release()

[[1.0000000e+00 3.4644483e-23]]
[[1.0000000e+00 1.1997513e-10]]
[[9.9997818e-01 1.8582259e-04]]
[[1.000000e+00 2.080539e-13]]
[[1.000000e+00 7.753675e-10]]
[[1.0000000e+00 5.3994816e-21]]
[[1.0000000e+00 1.3180496e-16]]
[[1.0000000e+00 3.6972496e-25]]
[[1.0000000e+00 4.1114526e-15]]
[[1.0000000e+00 8.7230337e-13]]
[[1.000000e+00 1.590151e-15]]
[[1.0000000e+00 1.2455312e-12]]
[[1.000000e+00 6.561747e-21]]
[[1.000000e+00 7.499182e-14]]
[[1.000000e+00 9.583485e-13]]
[[1.000000e+00 2.352404e-16]]
[[1.0000000e+00 1.0006958e-20]]
[[1.0000000e+00 7.3243865e-18]]
[[1.00000000e+00 1.02882667e-16]]
[[1.0000000e+00 3.7591187e-11]]
[[1.0000000e+00 8.4869394e-12]]
[[1.0000000e+00 5.9005553e-24]]
[[1.0000000e+00 1.3269729e-14]]
[[1.0000000e+00 2.3037766e-21]]
[[1.0000000e+00 1.7625202e-17]]
[[1.000000e+00 6.087098e-15]]
[[1.000000e+00 5.122961e-21]]
[[1.0000000e+00 5.6173975e-22]]
[[1.0000000e+00 1.5714797e-17]]
[[1.0000000e+00 1.0096915e-20]]
[[1.000000e+00 8.308999e-17]]
[[1.0000000e+00 3.9572702e

In [13]:
photo.shape

(480, 640, 3)

In [ ]:
def face_extract(img):
    face_cor =face_model.detectMultiScale(img)
    if len(face_cor)==0:
        return None
    else:
        (x,y,w,h)=face_cor[0]
        cv2.rectangle(photo ,(x,y),(x+w ,y+h) ,[0,255,255] ,3)
        crop_img=img[y:y+h ,x:x+w]
        return crop_img

###### 